package com.otp.touristplanner.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.otp.touristplanner.entity.TourPackage;
import com.otp.touristplanner.repository.PackageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.util.stream.Stream;

@Service
public class ItineraryService {

    @Autowired
    private PackageRepository packageRepository;

    @Transactional(readOnly = true)
    public byte[] generatePackageItinerary(Long packageId) throws Exception {
        TourPackage pkg = packageRepository.findById(packageId)
                .orElseThrow(() -> new RuntimeException("Package not found"));

        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);

        document.open();

        // Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, BaseColor.DARK_GRAY);
        Paragraph title = new Paragraph("Travel Itinerary: " + pkg.getDestinationName(), titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(30);
        document.add(title);

        // Package Overview Table
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        addTableHeader(table, "Feature", "Details");
        addRow(table, "Duration", pkg.getNumberOfDays() + " Days / " + pkg.getNumberOfNights() + " Nights");
        addRow(table, "Capacity", pkg.getPackageCapacity() + " Persons");
        addRow(table, "Base Price", "Rs. " + pkg.getPrice());
        document.add(table);

        document.add(new Paragraph("\n"));

        // Sections
        addSection(document, "🍽️ Food & Dining", pkg.getFoodDetails());
        addSection(document, "🏨 Stay & Accommodation", pkg.getAccommodationDetails());
        addSection(document, "🎯 Sightseeing & Activities", pkg.getSightseeingDetails());
        addSection(document, "📝 Description", pkg.getDescription());

        // Footer
        Paragraph footer = new Paragraph("\n\nGenerated by Online Tourist Planner",
                FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.LIGHT_GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addTableHeader(PdfPTable table, String col1, String col2) {
        Stream.of(col1, col2).forEach(columnTitle -> {
            PdfPCell header = new PdfPCell();
            header.setBackgroundColor(BaseColor.LIGHT_GRAY);
            header.setBorderWidth(2);
            header.setPhrase(new Phrase(columnTitle, FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
            header.setPadding(8);
            table.addCell(header);
        });
    }

    private void addRow(PdfPTable table, String col1, String col2) {
        table.addCell(new Phrase(col1));
        table.addCell(new Phrase(col2));
    }

    private void addSection(Document document, String title, String content) throws DocumentException {
        Font sectionTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
        Paragraph sectionTitle = new Paragraph(title, sectionTitleFont);
        sectionTitle.setSpacingBefore(10);
        sectionTitle.setSpacingAfter(5);
        document.add(sectionTitle);

        Font contentFont = FontFactory.getFont(FontFactory.HELVETICA, 11, BaseColor.GRAY);
        Paragraph sectionContent = new Paragraph(content != null ? content : "Not specified", contentFont);
        sectionContent.setSpacingAfter(15);
        document.add(sectionContent);
    }
}
